import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { z } from "zod";
import { addDays, format } from "date-fns";

const generateLetterSchema = z.object({
  invoiceId: z.string().min(1),
});

export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json(
        { success: false, error: { code: "UNAUTHORIZED", message: "Authentication required" } },
        { status: 401 }
      );
    }

    const body = await request.json();
    const parsed = generateLetterSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { success: false, error: { code: "VALIDATION_ERROR", message: parsed.error.errors[0]?.message || "Invalid input" } },
        { status: 422 }
      );
    }

    // Get invoice with client data
    const invoice = await prisma.invoice.findFirst({
      where: { id: parsed.data.invoiceId, userId: session.user.id, deletedAt: null },
      include: {
        client: true,
        reminders: { orderBy: { sentAt: "desc" }, take: 10 },
        legalEscalation: true,
      },
    });

    if (!invoice) {
      return NextResponse.json(
        { success: false, error: { code: "NOT_FOUND", message: "Invoice not found" } },
        { status: 404 }
      );
    }

    // Check Premium
    const subscription = await prisma.subscription.findUnique({
      where: { userId: session.user.id },
      include: { plan: true },
    });

    if (!subscription?.plan?.legalEscalationEnabled) {
      return NextResponse.json(
        { success: false, error: { code: "PAYMENT_REQUIRED", message: "Legal escalation requires a Premium plan" } },
        { status: 402 }
      );
    }

    // Get user data
    const user = await prisma.user.findUnique({ where: { id: session.user.id } });

    const daysOverdue = Math.floor(
      (new Date().getTime() - new Date(invoice.dueDate).getTime()) / (1000 * 60 * 60 * 24)
    );

    const sentReminderDates = invoice.reminders
      .filter((r) => r.sentAt)
      .map((r) => format(new Date(r.sentAt!), "MMM d, yyyy"))
      .join(", ");

    const formattedAmount = new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: invoice.currency,
    }).format(Number(invoice.amount));

    const today = format(new Date(), "MMMM d, yyyy");
    const deadline = format(addDays(new Date(), 7), "MMMM d, yyyy");

    const letter = `${today}

VIA EMAIL

${invoice.client.name}
${invoice.client.company || ""}
${invoice.client.email}

Re: FINAL DEMAND FOR PAYMENT — Invoice ${invoice.invoiceNumber}

Dear ${invoice.client.name},

This letter serves as a formal demand for payment of the outstanding balance of ${formattedAmount} for services rendered as detailed in Invoice ${invoice.invoiceNumber}, dated ${format(new Date(invoice.createdAt), "MMMM d, yyyy")}.

Despite multiple reminders sent on ${sentReminderDates || "various dates"}, the amount remains unpaid and is now ${daysOverdue} days past due.

UNLESS PAYMENT IS RECEIVED IN FULL by ${deadline} (7 calendar days from the date of this letter), the following actions will be taken without further notice:

1. File a claim in small claims court
2. Report this debt to credit reporting agencies
3. Pursue all available legal remedies to collect the amount owed

We prefer to resolve this matter amicably, but we are prepared to pursue all legal options if necessary.

Please remit payment via your preferred method immediately.

Sincerely,

${user?.name || session.user.name || "Sender"}
${user?.name || "Freelancer"}

---

This letter was generated by DeathFear on behalf of ${user?.name || session.user.name || "the sender"}.`;

    // Upsert legal escalation
    const escalation = await prisma.legalEscalation.upsert({
      where: { invoiceId: invoice.id },
      update: {
        formalLetterGenerated: true,
        formalLetterContent: letter,
        status: "letter_generated",
      },
      create: {
        invoiceId: invoice.id,
        userId: session.user.id,
        formalLetterGenerated: true,
        formalLetterContent: letter,
        status: "letter_generated",
      },
    });

    // Log notification
    await prisma.notificationLog.create({
      data: {
        userId: session.user.id,
        type: "legal_letter_generated",
        email: invoice.client.email,
        subject: `Formal Demand Letter — Invoice ${invoice.invoiceNumber}`,
        body: letter.substring(0, 500),
        metadata: JSON.stringify({ invoiceId: invoice.id, escalationId: escalation.id }),
      },
    });

    return NextResponse.json({ success: true, data: { letter, escalation } });
  } catch (error) {
    console.error("Error generating legal letter:", error);
    return NextResponse.json(
      { success: false, error: { code: "INTERNAL_ERROR", message: "Failed to generate legal letter" } },
      { status: 500 }
    );
  }
}
