export default function TermsPage() {
  return (
    <div className="container mx-auto max-w-3xl py-12 px-4">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      
      <div className="prose prose-gray dark:prose-invert max-w-none space-y-6">
        <p className="text-muted-foreground">
          Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
        </p>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground">
            By creating a DeathFear account, you agree to be bound by these Terms of Service. 
            If you do not agree, do not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">2. Description of Service</h2>
          <p className="text-muted-foreground">
            DeathFear is a SaaS platform that helps freelancers recover unpaid invoices by automating 
            payment reminders, AI-powered tone adaptation, and legal escalation document generation. 
            The service includes invoice creation, automated reminder sequences, client management, 
            and legal document templates.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">3. User Responsibilities</h2>
          <p className="text-muted-foreground">As a user of DeathFear, you agree to:</p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2 mt-2">
            <li>Provide accurate information when creating your account</li>
            <li>Maintain the confidentiality of your account credentials</li>
            <li>Ensure you have the right to send emails to your clients via our service</li>
            <li>Comply with all applicable laws, including anti-spam regulations (CAN-SPAM Act, GDPR, etc.)</li>
            <li>Not use the service for any illegal purpose or to harass others</li>
            <li>Take responsibility for the content of reminder messages sent through the platform</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">4. Subscription and Billing</h2>
          <p className="text-muted-foreground">
            DeathFear offers Free and Premium subscription plans. By subscribing to Premium, you agree to:
          </p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2 mt-2">
            <li>Pay the applicable fees at the beginning of each billing period</li>
            <li>Provide valid payment information (credit card, PayPal, or UPI AutoPay)</li>
            <li>Understand that fees are non-refundable except as required by law</li>
            <li>Receive email receipts for all payments</li>
          </ul>
          <p className="text-muted-foreground mt-4">
            Premium subscriptions automatically renew unless canceled before the renewal date. 
            You can cancel at any time from your billing settings. Upon cancellation, 
            you retain Premium access until the end of your current billing period.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">5. Free Plan Limits</h2>
          <p className="text-muted-foreground">
            Free plan users are limited to 3 invoices per month and 5 clients. 
            If you exceed these limits, you will be prompted to upgrade to Premium. 
            Existing data remains accessible, but creating new invoices or clients is restricted until you upgrade or the next billing cycle.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">6. AI Tone Adaptation</h2>
          <p className="text-muted-foreground">
            The AI tone adaptation feature (Premium) uses OpenAI to rewrite reminder messages in the user&apos;s voice. 
            You are responsible for reviewing AI-generated content before sending. 
            DeathFear is not responsible for the content generated by AI. 
            Each Premium user is limited to 50 AI generations per month.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">7. Legal Escalation</h2>
          <p className="text-muted-foreground">
            DeathFear provides templates for formal demand letters and small claims filing guides for informational purposes only. 
            These do not constitute legal advice. We strongly recommend consulting with a licensed attorney 
            before taking any legal action. DeathFear is not a law firm and does not provide legal services.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">8. Limitation of Liability</h2>
          <p className="text-muted-foreground">
            DeathFear is provided &quot;as is&quot; without warranty of any kind. We are not liable for any damages 
            arising from your use of the service, including but not limited to: failure to recover payment, 
            legal outcomes, email delivery failures, or data loss. Our total liability is limited to 
            the amount you paid for the service in the 12 months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">9. Account Termination</h2>
          <p className="text-muted-foreground">
            We reserve the right to suspend or terminate accounts that violate these terms 
            or engage in abusive behavior. You can delete your account at any time from Settings.
            Upon deletion, your data is soft-deleted for 30 days and then permanently removed.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">10. Changes to Terms</h2>
          <p className="text-muted-foreground">
            We may update these terms from time to time. Material changes will be notified via email. 
            Continued use of the service after changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-8 mb-4">11. Contact</h2>
          <p className="text-muted-foreground">
            For questions about these terms, contact us at legal@deathear.app.
          </p>
        </section>
      </div>
    </div>
  );
}
